---
# file: group_vars/gateways.yml

gateway_packages:
  - mtr-tiny
  - tcpdump
  - batctl
  - fastd
  - git
  - haveged
  - bridge-utils
  - ferm
  - iptables-persistent
  - net-tools
  - iftop
  - tcpdump

gateway_users:
  - omni
  - quite

fastd_port: 10006
