---
# file: roles/gateway/vars/main.yml

gateway_packages:
  - mtr-tiny
  - tcpdump
  - batctl
  - fastd
  - git
  - haveged
  - bridge-utils
  - ferm
  - iptables-persistent
  - net-tools
  - iftop

gateway_users:
  - omni
  - quite
