---
# file: roles/gateway/tasks/batman.yml

- name: Enable batman-adv module
  copy:
    src: 'etc/modules-load.d/batman.conf'
    dest: '/etc/modules-load.d/batman.conf'
    owner: root
    group: root
    mode: 0644
