---
# file: roles/gateway/tasks/firewall.yml

- name: ferm.conf
  template:
    src: 'ferm.conf.j2'
    dest: '/etc/ferm/ferm.conf'
    owner: root
    group: adm
    mode: 0644
  notify: run ferm

- name: Allow IP forwarding (sysctl, IPv4 & IPv6)
  sysctl:
    name: "{{ item }}"
    value: 1
    reload: yes
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
