---
# file: roles/gateway/tasks/firewall.yml

- name: ferm.conf
  template:
    src: 'ferm.conf.j2'
    dest: '/etc/ferm/ferm.conf'
    owner: root
    group: adm
    mode: 0644
  notify: run ferm

- name: sysctl net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: yes

- name: sysctl net.ipv6.conf.all.forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    reload: yes
