---
# file: roles/gateway/tasks/main.yml

- import_tasks: packages.yml
- import_tasks: interfaces.yml
- import_tasks: firewall.yml
- import_tasks: fastd.yml
- import_tasks: batman.yml
- import_tasks: dhcpd.yml
