---
# file: roles/gateway/tasks/main.yml

- name: Authorized keys
  authorized_key:
    key: "{{ lookup('file', 'user_keys/{{ item }}') }}"
    user: "{{ item }}"
  with_items: "{{ gateway_users }}"

- name: Setup Debian Backports repo
  apt_repository:
    repo: deb http://ftp.se.debian.org/debian/ stretch-backports main
    state: present

- name: Install packages
  apt: pkg={{ item }} state=latest update-cache=yes
  with_items: "{{ gateway_packages }}"

- name: ferm.conf
  template:
    src: 'ferm.conf.j2'
    dest: '/etc/ferm/ferm.conf'
    owner: root
    group: adm
    mode: 0644
  notify: run ferm

- name: Checkout our fastd peers from github
  git:
    repo: https://github.com/pjodd/gluon-gateway-peers.git
    dest: /etc/fastd/vpn/peers

- name: Generate fastd secret, if none (chmoded 0600)
  fastd_key: path=/etc/fastd/vpn/secret.conf

- name: fastd.conf
  template:
    src: 'fastd.conf.j2'
    dest: '/etc/fastd/vpn/fastd.conf'
    owner: root
    group: root
    mode: 0644

- name: fastd enabled & (re)started
  service: name=fastd enabled=yes state=restarted

- name: sysctl net.ipv4.ip_forward
  sysctl: name=net.ipv4.ip_forward value=1

- name: sysctl net.ipv6.conf.all.forwarding
  sysctl: name=net.ipv6.conf.all.forwarding value=1

- name: Enable batman-adv module
  copy:
    src: 'etc/modules-load.d/batman.conf'
    dest: '/etc/modules-load.d/batman.conf'
    owner: root
    group: root
    mode: 0644
