---
# file: setup-sudo.yml
- hosts: debians
  gather_facts: false
  become: yes
  become_method: su

  tasks:
    - name: Install sudo
      apt:
        update_cache: yes
        name: sudo
        state: present
    - name: Add users to sudo group
      user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: adm,sudo
        append: yes
      with_items: "{{ gateway_users }}"
